
package stubs.cycle;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Demo", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/demo/cycle/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Demo {


    /**
     * 
     * @return
     *     returns java.util.List<stubs.cycle.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listCustomers", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/demo/cycle/", className = "stubs.cycle.ListCustomers")
    @ResponseWrapper(localName = "listCustomersResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/demo/cycle/", className = "stubs.cycle.ListCustomersResponse")
    public List<Customer> listCustomers();

}
